### ISSUE TITLE
If I can help :)

### ISSUE THREAD

**Issue by pascalandy** [dcefram/stupendous#3]
Hi Daniel,
Very good job on this theme! I’m the owner of [play-with-ghost](http://play-with-ghost.com/) and one big feature I'm working on is to showcase templates I enjoy like yours. 

Let me know if I can help you by hosting a staging environment of your Ghost project(s) or anything related of the backend of hosting Ghost.

Cheers!
[Pascal](https://twitter.com/askpascalandy/)

**Comment by ghost** [comment]
Thanks, it would be flattering if you would showcase my template :D If ever you do showcase this template on your server, I think it would make sense to update this project's README and point the demo to your showcase.

I'm not sure if I would have more Ghost projects aside from this one as of now, since I primarily created this template for my own blog.

**Comment by pascalandy** [comment]
Very good! I'll put it on #pwg. I really love your theme. Will let you know when it's up :)

**Comment by pascalandy** [comment]
Still on the case! DevOps is much more work than planned! I'll let you know!

**Comment by pascalandy** [comment]
It's been a while it's online. I just forgot to mention it here!

https://play-with-ghost.com/ghost-themes/firepress-stupendous-for-barbershops/

If it works for you, let me know, I'll do a PR on your readme :)
Cheers!

**Comment by ghost** [comment]
Thanks :) I'll close this issue then :D
